// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.31.1
// source: api/example/v1/example.proto

package example

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationExampleSignIn = "/Example.Example/SignIn"
const OperationExampleSignUp = "/Example.Example/SignUp"

type ExampleHTTPServer interface {
	// SignInpost方法示例规范
	// 用户登录
	SignIn(context.Context, *SignInReq) (*Response, error)
	// SignUp每个接口独立注释，并且采用http和grpc双协议定义（除非接口文档中明确说明不用映射http）
	//get方法示例规范
	SignUp(context.Context, *SignUpReq) (*Response, error)
}

func RegisterExampleHTTPServer(s *http.Server, srv ExampleHTTPServer) {
	r := s.Route("/")
	r.POST("/auth/signup", _Example_SignUp0_HTTP_Handler(srv))
	r.POST("/auth/sign_in", _Example_SignIn0_HTTP_Handler(srv))
}

func _Example_SignUp0_HTTP_Handler(srv ExampleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SignUpReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExampleSignUp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SignUp(ctx, req.(*SignUpReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Response)
		return ctx.Result(200, reply)
	}
}

func _Example_SignIn0_HTTP_Handler(srv ExampleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SignInReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExampleSignIn)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SignIn(ctx, req.(*SignInReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Response)
		return ctx.Result(200, reply)
	}
}

type ExampleHTTPClient interface {
	SignIn(ctx context.Context, req *SignInReq, opts ...http.CallOption) (rsp *Response, err error)
	SignUp(ctx context.Context, req *SignUpReq, opts ...http.CallOption) (rsp *Response, err error)
}

type ExampleHTTPClientImpl struct {
	cc *http.Client
}

func NewExampleHTTPClient(client *http.Client) ExampleHTTPClient {
	return &ExampleHTTPClientImpl{client}
}

func (c *ExampleHTTPClientImpl) SignIn(ctx context.Context, in *SignInReq, opts ...http.CallOption) (*Response, error) {
	var out Response
	pattern := "/auth/sign_in"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationExampleSignIn))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ExampleHTTPClientImpl) SignUp(ctx context.Context, in *SignUpReq, opts ...http.CallOption) (*Response, error) {
	var out Response
	pattern := "/auth/signup"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationExampleSignUp))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
